from django.conf import settings
from constants import DEFAULT_ZIPKIN_DATA_STORE_CLASS, DEFAULT_ZIPKIN_LOGGER_NAME, \
    DEFAULT_ZIPKIN_SERVICE_NAME, DEFAULT_ZIPKIN_ID_GENERATOR_CLASS, \
    DEFAULT_ZIPKIN_SCRIBE_ENABLE, DEFAULT_ZIPKIN_HOST, DEFAULT_ZIPKIN_PORT

ZIPKIN_SERVICE_NAME = getattr(settings, 'ZIPKIN_SERVICE_NAME', DEFAULT_ZIPKIN_SERVICE_NAME)
ZIPKIN_LOGGER_NAME = getattr(settings, 'ZIPKIN_LOGGER_NAME', DEFAULT_ZIPKIN_LOGGER_NAME)
ZIPKIN_DATA_STORE_CLASS = getattr(settings, 'ZIPKIN_DATA_STORE_CLASS', DEFAULT_ZIPKIN_DATA_STORE_CLASS)
ZIPKIN_ID_GENERATOR_CLASS = getattr(settings, 'ZIPKIN_ID_GENERATOR_CLASS', DEFAULT_ZIPKIN_ID_GENERATOR_CLASS)
ZIPKIN_SCRIBE_ENABLE = getattr(settings, 'ZIPKIN_SCRIBE_ENABLE', DEFAULT_ZIPKIN_SCRIBE_ENABLE)
ZIPKIN_HOST = getattr(settings, 'ZIPKIN_HOST', DEFAULT_ZIPKIN_HOST)
ZIPKIN_PORT = getattr(settings, 'ZIPKIN_PORT', DEFAULT_ZIPKIN_PORT)
